[package]
name = "collating-iterator"
version = "1.0.0"
edition = "2021"
authors = ["Research Artifact"]
license = "MIT"

[lib]
name = "collating_iterator"
path = "src/lib.rs"

[dependencies]

[dev-dependencies]

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
